sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lauromueller/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lauromueller/docker-react npm run test